{ name: "Zelalem Araya", role: "Advisor", image: "/people/zela.png", roleEmoji: "💭" },
{ name: "Brian Yang", role: "Co-President", image: "/people/brian.png", roleEmoji: "⭐" },
{ name: "Jackie Crowley", role: "Co-President", image: "/people/jackie.png", roleEmoji: "⭐" },
{ name: "Elisabeth Lau", role: "VP Logistics", image: "/people/Elisabeth.png", roleEmoji: "⭐" },
{ name: "Elaine Li", role: "VP Partnerships", image: "/people/elaine.jpeg", roleEmoji: "⭐" },
{ name: "Aurora Cheng", role: "VP Marketing Design", image: "/people/aurora.png", roleEmoji: "⭐" },
{ name: "Erin Chiu", role: "Co-Treasurer", image: "/people/erin.png", roleEmoji: "💵" },
{ name: "Owen Li", role: "Co-Treasurer", image: "/people/owen.png", roleEmoji: "💵" },
{ name: "Taro Ren", role: "VP Internal", image: "/people/taro.jpeg", roleEmoji: "🎉" },
{ name: "Aubrey Ventura", role: "Design Director", image: "/people/aubrey.png", roleEmoji: "🎨" },
{ name: "Martin Uy", role: "Design Director", image: "/people/martin.png", roleEmoji: "🎨" },
{ name: "David Theopine", role: "Design Director", image: "/people/david.png", roleEmoji: "🎨" },
{ name: "Chhavi", role: "Design Director", image: "/people/chhavi.jpeg", roleEmoji: "🎨" },
{ name: "Iris Liu", role: "Media Director", image: "/people/iris.png", roleEmoji: "🎬" },
{ name: "Mason Suen", role: "Media Director", image: "/people/mason.png", roleEmoji: "🎬" },
{ name: "Cherry Wang", role: "Media Director", image: "/people/cherry.png", roleEmoji: "🎬" },
{ name: "Marina Yu", role: "Media Director", image: "/people/marina.png", roleEmoji: "🎬" },
{ name: "Eric Yan", role: "Logistics Director", image: "/people/eric.png", roleEmoji: "💡" },
{ name: "Kazuma Uji", role: "Logistics Director", image: "/people/kazuma.png", roleEmoji: "💡" },
{ name: "Jessie Megan", role: "Logistics Director", image: "/people/jessie.png", roleEmoji: "💡" },
{ name: "Mia Makino", role: "Logistics Director", image: "/people/Mia.png", roleEmoji: "💡" },
{ name: "Carys Fong", role: "Logistics Director", image: "/people/carys.png", roleEmoji: "💡" },
{ name: "Raksha Zunnuru", role: "Logistics Director", image: "/people/raksha.png", roleEmoji: "💡" },
{ name: "Katrina Wei", role: "Partnerships Director", image: "/people/Kat.png", roleEmoji: "🤝" },
{ name: "Quang Mai", role: "Partnerships Director", image: "/people/quang.jpeg", roleEmoji: "🤝" },
{ name: "Johnny Dong", role: "Developer", image: "/people/johnny.png", roleEmoji: "💻" },
